### ISSUE TITLE
Create Comment Component

### ISSUE THREAD

**Issue by Monilprajapati** [Monilprajapati/Connectiify#14]
- [ ] Create the Comment Input box to add the comment
- [ ] Create comment message component to show case the comment of any user
- [ ] Add comment Upvote and downvote functionalities to it

**Comment by UmangDalvadi** [comment]
> * [x]  Create the Comment Input box to add the comment
> * [x]  Create comment message component to show case the comment of any user
> * [x]  Add comment Upvote and downvote functionalities to it
