### ISSUE TITLE
Setup the Backend Structure with Database and server

### ISSUE THREAD

**Issue by Monilprajapati** [Monilprajapati/Connectiify#2]
- [ ] Connect the backend with MongoDB Database and express server
- [ ] Setup the utils folder to handle the errors 
- [ ] Create the basic folders such as Models, Controllers, Routes, Middlewawres
- [ ] Add .env.sample file to get to know about the variable that are in use

**Comment by kenil-kanani** [comment]
> * [x]  Connect the backend with MongoDB Database and express server
> * [x]  Setup the utils folder to handle the errors
> * [x]  Create the basic folders such as Models, Controllers, Routes, Middlewawres
> * [x]  Add .env.sample file to get to know about the variable that are in use

Done with set up
